workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "web"'

stages:
  - test
  - allure
  - commit

variables:
  ALLURE: "2.38.1"
  EXECUTOR_NAME: "Gitlab CI"
  EXECUTOR_TYPE: "gitlab"
  DOCKER:
    value: "harmin/qa-runner-debian"
    options:
      - "harmin/qa-runner-debian"
      - "harmin/qa-runner-ubuntu"
      - "harmin/qa-runner-debian:12"
      - "harmin/qa-runner-debian:beta"
    description: "The docker image to use."
  BROWSER:
    value: "firefox"
    options:
      - "chrome"
      - "chromium"
      - "firefox"
      - "msedge"
    description: "The browser to run the tests."
  PUBLISH:
    value: "false"
    options:
      - "true"
      - "false"
    description: "Whether to publish the reports."


tests:
  stage: test
  image: $DOCKER
  script:
    - python3 -m venv ~/venv
    - . ~/venv/bin/activate
    - ./runner.sh --browser $BROWSER
    - mkdir reports/allure-results
    - echo $CI_JOB_URL > reports/job.url
    - ./reports.sh
  artifacts:
    paths:
      - reports
    expire_in: 10 mins


allure2:
  stage: allure
  image: eclipse-temurin:8-jre
  script:
    - curl https://github.com/allure-framework/allure2/releases/download/${ALLURE}/allure-${ALLURE}.tgz -L -o /tmp/allure.tgz
    - tar -xzf /tmp/allure.tgz -C /usr/local
    - ln -s /usr/local/allure-${ALLURE}/bin/allure /usr/local/bin/allure
    - ./allure.sh --browser $BROWSER
  artifacts:
    paths:
      - report
    expire_in: 10 mins


allure3:
  stage: allure
  image: node:24
  script:
    - npm install allure
    - ./allure3.sh --browser $BROWSER
  artifacts:
    paths:
      - report
    expire_in: 10 mins


commit:
  stage: commit
  image: bitnami/git
  rules:
    - if: $PUBLISH == "true"
  before_script:
    - git config --global user.name "Gitlab CI"
    - git config --global user.email "gitlab@mg.gitlab.com"
  script:
    # - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/qa-demo/reports.git
    - git clone https://oauth2:${TOKEN}@gitlab.com/qa-demo/reports.git reports-repo
    - cd reports-repo
    - git rm -r report-*
    - git rm allure*-reports
    - rm -rf report-*
    - rm -rf allure*-reports
    - mv ../reports/report-* ./ || { echo "no report to commit"; exit; }
    - mv ../reports/allure*-reports ./ || { echo "no report to commit"; exit; }
    - git add *
    - git commit -m "Gitlab-CI commit"
    - git push


#pages:
#  stage: pages
#  script:
#    - mkdir public
#    - mv reporting/allure-reports/* public/
#    - mv reporting/report-* public/
#  artifacts:
#    paths:
#      - public
