[pytest]
addopts =
  --import-mode importlib
  --alluredir reports/allure-results
  --allure-link-pattern issue:https://issues.example.com/{}
  --allure-link-pattern tms:https://tms.example.com/{}
#  --headed
#  --slowmo 1000
