[pytest]
addopts =
  --capture=tee-sys
  --import-mode importlib
  --junitxml reports/report-junit/report.xml
  --alluredir reports/allure-results
  --allure-link-pattern issue:https://issues.example.com/{}
  --allure-link-pattern tms:https://tms.example.com/{}
#  --headed
#  --slowmo 1000

junit_family=xunit1
