name: cypress

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'chromium'
        required: true
        type: choice
        options:
        - chrome
        - chromium
        - edge
        - electron
        - firefox

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers
      options: --user 1001
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          ./docker.sh --browser "${{ inputs.browser }}" --docker cypress
          # echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} > reporting/allure-results/nodejs/job.url
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_test
          path: reporting
