name: java/serenity

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'firefox'
        required: true
        type: choice
        options:
        - chrome
        - firefox
        - edge

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: selenium/standalone-${{ inputs.browser }}
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          distribution: 'microsoft'
          java-version: '25'
      - name: Test
        run: |
          curl -L https://dlcdn.apache.org/maven/maven-3/3.9.8/binaries/apache-maven-3.9.8-bin.tar.gz -o maven-bin.tar.gz
          tar -xf maven-bin.tar.gz -C /tmp/
          M2_HOME='/tmp/apache-maven-3.9.8'
          PATH="$M2_HOME/bin:$PATH"
          export PATH
          ./docker.sh --browser "${{ inputs.browser }}" --test java/serenity
          echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} > reporting/allure-results/java/job.url
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_test
          path: reporting/
