name: python/playwright

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'chromium'
        required: true
        type: choice
        options:
        - chromium
        - firefox
        - webkit

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright/python:v1.55.0-noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      #- uses: actions/setup-node@v4
      #  with:
      #    node-version: '20'
      - name: Test execution
        run: |
          #export PATH=$PATH:$HOME/.local/bin
          #apt-get update && apt-get install -y python3-venv python3-pip
          mkdir reporting/allure-results/java reporting/allure-results/nodejs reporting/allure-results/python
          #python3 -m venv ~/venv
          #. ~/venv/bin/activate
          ./docker.sh --browser "${{ inputs.browser }}" --test python/playwright
          echo ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} > reporting/allure-results/python/job.url
        env:
          HOME: /root
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_test
          path: reporting/

  report:
    uses: ./.github/workflows/report-job.yml
    needs: [test]
    with:
      browser: ${{ inputs.browser }}
