name: robotframework/playwright

env:
  ALLURE: 2.34.1

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'chromium'
        required: true
        type: choice
        options:
        - chromium
        - firefox

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: marketsquare/robotframework-browser
      options: --user pwuser
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Test
        run: |
          ./docker.sh --browser "${{ inputs.browser }}" --docker robotframework/playwright
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_test
          path: reporting
